### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by NPellet** [cheminfo/nmrdb#15]
CSS issue somewhere. Hing: my window was kind of small when I loaded the visualizer.

![screen shot 2014-09-10 at 23 18 19](https://cloud.githubusercontent.com/assets/1484251/4229940/8514a5f8-397b-11e4-919c-0dd6241069fe.png)

**Comment by stropitek** [comment]
This should be fixed in release v2.13.0 of the visualizer.
We should migrate views and test it.
